In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'C:\Users\ahmed\Desktop\MediaPipe\Project\landmarks pose dataset.csv')
df.head()

,image,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Roll,Pitch,Yaw
0,image00002.jpg,220,287,159,198,181,306,216,363,301,...,316,217,372,128,202,337,223,-22.874237,1.044306,4.908885
1,image00004.jpg,187,266,209,224,201,298,211,326,265,...,302,220,338,241,244,337,252,26.932741,68.155235,17.243670
2,image00006.jpg,144,349,109,322,123,363,142,386,168,...,362,142,393,89,331,179,329,-10.579652,50.485409,-13.570644
3,image00008.jpg,211,294,159,241,211,318,251,351,270,...,302,260,361,167,252,327,200,-10.048455,17.143373,-21.392782
4,image00013.jpg,221,272,158,229,205,318,242,354,273,...,305,247,371,134,267,319,226,-1.536199,0.685565,-12.643007

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1853 entries, 0 to 1852
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   image   1853 non-null   object
 1   X1      1853 non-null   int64
 2   X2      1853 non-null   int64
 3   X3      1853 non-null   int64
 4   X4      1853 non-null   int64
 5   X5      1853 non-null   int64
 6   X6      1853 non-null   int64
 7   X7      1853 non-null   int64
 8   X8      1853 non-null   int64
 9   X9      1853 non-null   int64
 10  Y1      1853 non-null   int64
 11  Y2      1853 non-null   int64
 12  Y3      1853 non-null   int64
 13  Y4      1853 non-null   int64
 14  Y5      1853 non-null   int64
 15  Y6      1853 non-null   int64
 16  Y7      1853 non-null   int64
 17  Y8      1853 non-null   int64
 18  Y9      1853 non-null   int64
 19  Roll    1853 non-null   float64
 20  Pitch   1853 non-null   float64
 21  Yaw     1853 non-null   float64
dtypes: float64(3), int64(18), object(1)
memory usage: 318.6+ KB

In [4]:
df.drop(columns = 'image', axis = 1, inplace = True)

In [5]:
features = df.drop(columns=['Roll', 'Pitch', 'Yaw'])
targets = ['Roll', 'Pitch', 'Yaw']

In [6]:
models = {}
results = {}

for target in targets:
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(features, df[target], test_size = 0.2, random_state = 42)

    # scale independent features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test  = scaler.fit_transform(X_test)

    # Train Model
    model = RandomForestRegressor(n_estimators = 100, random_state = 42)
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Evaluate
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Store Model and Results
    models[target] = model
    results[target] = {'MSE': mse, 'MAE': mae, 'R2': r2}

for target, metrics in results.items():
    print(f"Model for {target}:")
    print(metrics)
    print("-" * 80)

Model for Roll:
{'MSE': 78.44102116751047, 'MAE': 5.549742772294753, 'R2': 0.672628811253649}
--------------------------------------------------------------------------------
Model for Pitch:
{'MSE': 56.93454587744188, 'MAE': 4.7271840695047205, 'R2': 0.9314807813561994}
--------------------------------------------------------------------------------
Model for Yaw:
{'MSE': 71.90474184220291, 'MAE': 4.074547190164821, 'R2': 0.7826172646901127}
--------------------------------------------------------------------------------